version: "3"

services:
  app:
    container_name: "serializer_service"
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app/src
    ports:
      - 8200:8000
    env_file:
      - .env      


